from __future__ import annotations

import logging

from app.conflict.models import ConflictReport
from app.github_client.client import get_pr_commits, get_pr_diff, get_repo, post_comment
#mar15 removed duplicate OpenAICompatClient import
from app.llm.openai_compat import OpenAICompatClient
from app.llm.prompts import PR_SUMMARY_SYSTEM, PR_SUMMARY_USER
from app.notifications.slack import send_slack_pr_summary
from app.utils.git_ops import truncate_diff
from config import settings


logger = logging.getLogger(__name__)


def _get_llm() -> OpenAICompatClient:
    #mar15 use settings with fallback instead of hardcoded hackathon URL
    return OpenAICompatClient(
        api_base=settings.llm_api_base,
        api_key=settings.llm_api_key,
        model=settings.llm_model,
    )


#mar15 format cross-branch conflict info for inclusion in PR summary comment
def _format_conflict_section(conflict_reports: list[ConflictReport] | None) -> str:
    """Build a markdown section summarizing cross-branch conflicts, if any."""
    if not conflict_reports:
        return ""

    reports_with_conflicts = [r for r in conflict_reports if r.conflicts]
    if not reports_with_conflicts:
        return "**Conflicts:** None detected\n\n"

    lines = ["### Cross-Branch Conflicts\n"]
    for report in reports_with_conflicts:
        merge_count = sum(1 for c in report.conflicts if c.conflict_type == "merge")
        semantic_count = sum(1 for c in report.conflicts if c.conflict_type == "semantic")
        high_count = sum(1 for c in report.conflicts if c.severity == "high")

        branch_b = report.branch_b.replace("origin/", "")
        parts = []
        if merge_count:
            parts.append(f"{merge_count} merge")
        if semantic_count:
            parts.append(f"{semantic_count} semantic")
        severity_note = f" ({high_count} high severity)" if high_count else ""

        lines.append(
            f"- **`{branch_b}`** — {', '.join(parts)} conflict(s){severity_note}"
        )

        # List affected files
        files = sorted(set(c.file_path for c in report.conflicts))
        for f in files[:5]:
            lines.append(f"  - `{f}`")
        if len(files) > 5:
            lines.append(f"  - ... and {len(files) - 5} more")

    lines.append("")
    return "\n".join(lines) + "\n"


#mar15 added conflict_reports param to include cross-branch conflict info in summary
async def on_pr_summarize(
    payload: dict,
    token: str | None = None,
    conflict_reports: list[ConflictReport] | None = None,
) -> None:
    """Handle a pull_request event — generate and post a PR summary."""
    pr_data = payload.get("pull_request", {})
    if not pr_data:
        return

    repo_full_name = payload["repository"]["full_name"]
    pr_number = pr_data["number"]
    pr_title = pr_data.get("title", "")
    author = pr_data.get("user", {}).get("login", "unknown")
    #mar15 added sender tracking for audit logging
    sender = payload.get("sender", {}).get("login", "unknown")
    base_branch = pr_data["base"]["ref"]
    head_branch = pr_data["head"]["ref"]

    #mar15 restored repo/PR log line alongside new sender log
    logger.info("Generating PR summary for %s#%d", repo_full_name, pr_number)
    logger.info("PR author=%s triggered_by=%s", author, sender)

    repo = get_repo(repo_full_name, token)

    # Gather context
    diff_content = get_pr_diff(repo, pr_number)
    commit_messages = get_pr_commits(repo, pr_number)

    # Count stats from diff
    lines_added = diff_content.count("\n+") - diff_content.count("\n+++")
    lines_removed = diff_content.count("\n-") - diff_content.count("\n---")
    files_changed = diff_content.count("\n--- a/")

    # Truncate diff for LLM
    diff_truncated = truncate_diff(diff_content, max_lines=3000)

    user_prompt = PR_SUMMARY_USER.format(
        pr_number=pr_number,
        pr_title=pr_title,
        author=author,
        base_branch=base_branch,
        head_branch=head_branch,
        commit_messages="\n".join(f"- {m}" for m in commit_messages),
        files_changed=files_changed,
        lines_added=lines_added,
        lines_removed=lines_removed,
        diff_content=diff_truncated,
    )

    try:
        llm = _get_llm()
        summary_md = await llm.complete(PR_SUMMARY_SYSTEM, user_prompt)

        #mar15 build cross-branch conflict section from conflict reports
        conflict_section = _format_conflict_section(conflict_reports)

        # Wrap with header and footer
        comment = (
            f"## PR Summary\n\n"
            f"{summary_md}\n\n"
            f"**Stats:** {files_changed} files changed · "
            f"+{lines_added} / -{lines_removed}\n\n"
            f"{conflict_section}"
            f"---\n*Generated by [github-conflict-ai]*"
        )

        post_comment(repo, pr_number, comment)
        logger.info("Posted PR summary for %s#%d", repo_full_name, pr_number)

        # Also send to Slack
        await send_slack_pr_summary(repo_full_name, pr_number, pr_title, summary_md)

    except Exception:
        logger.exception("Failed to generate PR summary for %s#%d", repo_full_name, pr_number)
