import logging

from app.github_client.client import get_pr_commits, get_pr_diff, get_repo, post_comment
from app.llm.openai_compat import OpenAICompatClient
from app.llm.prompts import PR_SUMMARY_SYSTEM, PR_SUMMARY_USER
from app.notifications.slack import send_slack_pr_summary
from app.utils.git_ops import truncate_diff
from config import settings
from app.llm.openai_compat import OpenAICompatClient


logger = logging.getLogger(__name__)


def _get_llm() -> OpenAICompatClient:
    return OpenAICompatClient(
        api_base="https://vjioo4r1vyvcozuj.us-east-2.aws.endpoints.huggingface.cloud/v1",
        api_key="test",  # no real key needed
        model="openai/gpt-oss-120b",
    )


async def on_pr_summarize(payload: dict) -> None:
    """Handle a pull_request event — generate and post a PR summary."""
    pr_data = payload.get("pull_request", {})
    if not pr_data:
        return

    repo_full_name = payload["repository"]["full_name"]
    pr_number = pr_data["number"]
    pr_title = pr_data.get("title", "")
    author = pr_data.get("user", {}).get("login", "unknown")
    sender = payload.get("sender", {}).get("login", "unknown")
    base_branch = pr_data["base"]["ref"]
    head_branch = pr_data["head"]["ref"]

    logger.info("PR author=%s triggered_by=%s", author, sender)
    
    repo = get_repo(repo_full_name)

    # Gather context
    diff_content = get_pr_diff(repo, pr_number)
    commit_messages = get_pr_commits(repo, pr_number)

    # Count stats from diff
    lines_added = diff_content.count("\n+") - diff_content.count("\n+++")
    lines_removed = diff_content.count("\n-") - diff_content.count("\n---")
    files_changed = diff_content.count("\n--- a/")

    # Truncate diff for LLM
    diff_truncated = truncate_diff(diff_content, max_lines=3000)

    user_prompt = PR_SUMMARY_USER.format(
        pr_number=pr_number,
        pr_title=pr_title,
        author=author,
        base_branch=base_branch,
        head_branch=head_branch,
        commit_messages="\n".join(f"- {m}" for m in commit_messages),
        files_changed=files_changed,
        lines_added=lines_added,
        lines_removed=lines_removed,
        diff_content=diff_truncated,
    )

    try:
        llm = _get_llm()
        summary_md = await llm.complete(PR_SUMMARY_SYSTEM, user_prompt)

        # Wrap with header and footer
        comment = (
            f"## PR Summary\n\n"
            f"{summary_md}\n\n"
            f"**Stats:** {files_changed} files changed · "
            f"+{lines_added} / -{lines_removed}\n\n"
            f"---\n*Generated by [github-conflict-ai]*"
        )

        post_comment(repo, pr_number, comment)
        logger.info("Posted PR summary for %s#%d", repo_full_name, pr_number)

        # Also send to Slack
        await send_slack_pr_summary(repo_full_name, pr_number, pr_title, summary_md)

    except Exception:
        logger.exception("Failed to generate PR summary for %s#%d", repo_full_name, pr_number)
